apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cronjob
  namespace: cron-jobs
spec:
  schedule: "*/5 * * * *"
  timeZone: "Asia/Kolkata"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            image: busybox
            command:
              - sh
              - -c
              - date; echo "Hello from GitOps CronJob"
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
          restartPolicy: OnFailure
