apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: tekton-pipelines-app
    team: platform
spec:
  project: default
  source:
    repoURL: https://github.com/pawan-97/argocd-gitops.git
    targetRevision: master
    path: tekton-pipelines

  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-jobs

  syncPolicy:
    # Sync is manual — press the "Sync" button in ArgoCD UI to deploy
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
